<?php

    include_once("../includes/common_functions.php");
    include_once("../includes/var_definition.php");
    include_once("../includes/constants.php");
    include_once("../includes/db_$db_lib.php");
    date_default_timezone_set('America/Los_Angeles');
    
    mysql_connect($db_host.':'.$db_port, $db_user, $db_password);
    
    $db = new VA_SQL();
    $db->DBType      = $db_type;
    $db->DBDatabase  = $db_name;
    $db->DBHost      = $db_host;
    $db->DBPort      = $db_port;
    $db->DBUser      = $db_user;
    $db->DBPassword  = $db_password;
    $db->DBPersistent= $db_persistent;
    error_reporting(E_ALL);
if(isset($_REQUEST['order_id']) && is_numeric($_REQUEST['order_id']) ){
    
    $sql = "SELECT transaction_id FROM va_orders WHERE order_id = ".$_REQUEST['order_id']." AND order_status = 4";
    $db->query($sql);
    if($db->next_record()) {
        $url = "https://io.shipstation.com/Shipments()?\$filter=Order/OrderNumber%20eq%20'".$db->f("transaction_id")."'"; 
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Accept: application/json", "Accept-Charset: UTF-8"));
        curl_setopt($ch, CURLOPT_USERPWD, "cuttingedgestencils:sasha44");
        $xmlResponse = curl_exec($ch);
        //echo $xmlResponse;
        $SSdata = json_decode ($xmlResponse);
        $data = array('tracking_number' => $SSdata->d->results[0]->TrackingNumber);
        echo json_encode($data);
    }
}
else {
    $period = date('Y-m-d\TH:i:s', strtotime('-2 hour'));
    $url = "https://io.shipstation.com/Shipments()?\$filter=((Order/StoreID%20eq%201313)%20and%20(CreateDate%20gt%20datetime'".$period."'))&\$expand=Order";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Accept: application/json", "Accept-Charset: UTF-8"));
    curl_setopt($ch, CURLOPT_USERPWD, "cuttingedgestencils:sasha44");
    $response = curl_exec($ch);
//echo $response;
    $SSdata = json_decode($response);
    process_batch($SSdata);

    while(isset($SSdata->d->__next)){
        $url = str_replace("$", "\$", $SSdata->d->__next);
        curl_setopt($ch, CURLOPT_URL, $url);
        $response = curl_exec($ch);
        $SSdata = json_decode($response);
        process_batch($SSdata);
    }
}

function process_batch($data){
    global $db;
    
    $states["AL"] = 2;
    $states["AK"] = 1;
    $states["AS"] = 52;
    $states["AZ"] = 4;
    $states["AR"] = 3;
    $states["CA"] = 5;
    $states["CO"] = 6;
    $states["CT"] = 7;
    $states["DE"] = 9;
    $states["DC"] = 8;
    $states["FM"] = 53;
    $states["FL"] = 10;
    $states["GA"] = 11;
    $states["GU"] = 54;
    $states["HI"] = 12;
    $states["ID"] = 14;
    $states["IL"] = 15;
    $states["IN"] = 16;
    $states["IA"] = 13;
    $states["KS"] = 17;
    $states["KY"] = 18;
    $states["LA"] = 19;
    $states["ME"] = 22;
    $states["MH"] = 55;
    $states["MD"] = 21;
    $states["MA"] = 20;
    $states["MI"] = 23;
    $states["MN"] = 24;
    $states["MS"] = 26;
    $states["MO"] = 25;
    $states["MT"] = 27;
    $states["NE"] = 30;
    $states["NV"] = 34;
    $states["NH"] = 31;
    $states["NJ"] = 32;
    $states["NM"] = 33;
    $states["NY"] = 35;
    $states["NC"] = 28;
    $states["ND"] = 29;
    $states["MP"] = 56;
    $states["OH"] = 36;
    $states["OK"] = 37;
    $states["OR"] = 38;
    $states["PW"] = 57;
    $states["PA"] = 39;
    $states["PR"] = 58;
    $states["RI"] = 40;
    $states["SC"] = 41;
    $states["SD"] = 42;
    $states["TN"] = 43;
    $states["TX"] = 44;
    $states["UT"] = 45;
    $states["VT"] = 47;
    $states["VI"] = 59;
    $states["VA"] = 46;
    $states["WA"] = 48;
    $states["WV"] = 50;
    $states["WI"] = 49;
    $states["WY"] = 51;
    $states["AE"] = 60;
    
    $countries["AD"] = 1;
    $countries["AE"] = 2;
    $countries["AF"] = 3;
    $countries["AG"] = 4;
    $countries["AI"] = 5;
    $countries["AL"] = 6;
    $countries["AM"] = 7;
    $countries["AN"] = 8;
    $countries["AO"] = 9;
    $countries["AQ"] = 10;
    $countries["AR"] = 11;
    $countries["AS"] = 12;
    $countries["AT"] = 13;
    $countries["AU"] = 14;
    $countries["AW"] = 15;
    $countries["AX"] = 16;
    $countries["AZ"] = 17;
    $countries["BA"] = 18;
    $countries["BB"] = 19;
    $countries["BD"] = 20;
    $countries["BE"] = 21;
    $countries["BF"] = 22;
    $countries["BG"] = 23;
    $countries["BH"] = 24;
    $countries["BI"] = 25;
    $countries["BJ"] = 26;
    $countries["BM"] = 27;
    $countries["BN"] = 28;
    $countries["BO"] = 29;
    $countries["BR"] = 30;
    $countries["BS"] = 31;
    $countries["BT"] = 32;
    $countries["BV"] = 33;
    $countries["BW"] = 34;
    $countries["BY"] = 35;
    $countries["BZ"] = 36;
    $countries["CA"] = 37;
    $countries["CC"] = 38;
    $countries["CD"] = 39;
    $countries["CF"] = 40;
    $countries["CG"] = 41;
    $countries["CH"] = 42;
    $countries["CI"] = 43;
    $countries["CK"] = 44;
    $countries["CL"] = 45;
    $countries["CM"] = 46;
    $countries["CN"] = 47;
    $countries["CO"] = 48;
    $countries["CR"] = 49;
    $countries["RS"] = 50;
    $countries["CU"] = 51;
    $countries["CV"] = 52;
    $countries["CX"] = 53;
    $countries["CY"] = 54;
    $countries["CZ"] = 55;
    $countries["DE"] = 56;
    $countries["DJ"] = 57;
    $countries["DK"] = 58;
    $countries["DM"] = 59;
    $countries["DO"] = 60;
    $countries["DZ"] = 61;
    $countries["EC"] = 62;
    $countries["EE"] = 63;
    $countries["EG"] = 64;
    $countries["EH"] = 65;
    $countries["ER"] = 66;
    $countries["ES"] = 67;
    $countries["ET"] = 68;
    $countries["FI"] = 69;
    $countries["FJ"] = 70;
    $countries["FK"] = 71;
    $countries["FM"] = 72;
    $countries["FO"] = 73;
    $countries["FR"] = 74;
    $countries["GA"] = 76;
    $countries["GB"] = 77;
    $countries["GD"] = 78;
    $countries["GE"] = 79;
    $countries["GF"] = 80;
    $countries["GG"] = 81;
    $countries["GH"] = 82;
    $countries["GI"] = 83;
    $countries["GL"] = 84;
    $countries["GM"] = 85;
    $countries["GN"] = 86;
    $countries["GP"] = 87;
    $countries["GQ"] = 88;
    $countries["GR"] = 89;
    $countries["GS"] = 90;
    $countries["GT"] = 91;
    $countries["GU"] = 92;
    $countries["GW"] = 93;
    $countries["GY"] = 94;
    $countries["HK"] = 95;
    $countries["HM"] = 96;
    $countries["HN"] = 97;
    $countries["HR"] = 98;
    $countries["HT"] = 99;
    $countries["HU"] = 100;
    $countries["ID"] = 101;
    $countries["IE"] = 102;
    $countries["IL"] = 103;
    $countries["IM"] = 104;
    $countries["IN"] = 105;
    $countries["IO"] = 106;
    $countries["IQ"] = 107;
    $countries["IR"] = 108;
    $countries["IS"] = 109;
    $countries["IT"] = 110;
    $countries["JE"] = 111;
    $countries["JM"] = 112;
    $countries["JO"] = 113;
    $countries["JP"] = 114;
    $countries["KE"] = 115;
    $countries["KG"] = 116;
    $countries["KH"] = 117;
    $countries["KI"] = 118;
    $countries["KM"] = 119;
    $countries["KN"] = 120;
    $countries["KP"] = 121;
    $countries["KR"] = 122;
    $countries["KW"] = 123;
    $countries["KY"] = 124;
    $countries["KZ"] = 125;
    $countries["LA"] = 126;
    $countries["LB"] = 127;
    $countries["LC"] = 128;
    $countries["LI"] = 129;
    $countries["LK"] = 130;
    $countries["LR"] = 131;
    $countries["LS"] = 132;
    $countries["LT"] = 133;
    $countries["LU"] = 134;
    $countries["LV"] = 135;
    $countries["LY"] = 136;
    $countries["MA"] = 137;
    $countries["MC"] = 138;
    $countries["MD"] = 139;
    $countries["MG"] = 140;
    $countries["MH"] = 141;
    $countries["MK"] = 142;
    $countries["ML"] = 143;
    $countries["MM"] = 144;
    $countries["MN"] = 145;
    $countries["MO"] = 146;
    $countries["MP"] = 147;
    $countries["MQ"] = 148;
    $countries["MR"] = 149;
    $countries["MS"] = 150;
    $countries["MT"] = 151;
    $countries["MU"] = 152;
    $countries["MV"] = 153;
    $countries["MW"] = 154;
    $countries["MX"] = 155;
    $countries["MY"] = 156;
    $countries["MZ"] = 157;
    $countries["NA"] = 158;
    $countries["NC"] = 159;
    $countries["NE"] = 160;
    $countries["NF"] = 161;
    $countries["NG"] = 162;
    $countries["NI"] = 163;
    $countries["NL"] = 164;
    $countries["NO"] = 165;
    $countries["NP"] = 166;
    $countries["NR"] = 167;
    $countries["NU"] = 168;
    $countries["NZ"] = 169;
    $countries["OM"] = 170;
    $countries["PA"] = 171;
    $countries["PE"] = 172;
    $countries["PF"] = 173;
    $countries["PG"] = 174;
    $countries["PH"] = 175;
    $countries["PK"] = 176;
    $countries["PL"] = 177;
    $countries["PM"] = 178;
    $countries["PN"] = 179;
    $countries["PR"] = 180;
    $countries["PS"] = 181;
    $countries["PT"] = 182;
    $countries["PW"] = 183;
    $countries["PY"] = 184;
    $countries["QA"] = 185;
    $countries["RE"] = 186;
    $countries["RO"] = 187;
    $countries["RU"] = 188;
    $countries["RW"] = 189;
    $countries["SA"] = 190;
    $countries["SB"] = 191;
    $countries["SC"] = 192;
    $countries["SD"] = 193;
    $countries["SE"] = 194;
    $countries["SG"] = 195;
    $countries["SH"] = 196;
    $countries["SI"] = 197;
    $countries["SJ"] = 198;
    $countries["SK"] = 199;
    $countries["SL"] = 200;
    $countries["SM"] = 201;
    $countries["SN"] = 202;
    $countries["SO"] = 203;
    $countries["SR"] = 204;
    $countries["ST"] = 205;
    $countries["SV"] = 206;
    $countries["SY"] = 207;
    $countries["SZ"] = 208;
    $countries["TC"] = 209;
    $countries["TD"] = 210;
    $countries["TF"] = 211;
    $countries["TG"] = 212;
    $countries["TH"] = 213;
    $countries["TJ"] = 214;
    $countries["TK"] = 215;
    $countries["TL"] = 216;
    $countries["TM"] = 217;
    $countries["TN"] = 218;
    $countries["TO"] = 219;
    $countries["TR"] = 220;
    $countries["TT"] = 221;
    $countries["TV"] = 222;
    $countries["TW"] = 223;
    $countries["TZ"] = 224;
    $countries["UA"] = 225;
    $countries["UG"] = 226;
    $countries["UM"] = 227;
    $countries["US"] = 228;
    $countries["UY"] = 229;
    $countries["UZ"] = 230;
    $countries["VA"] = 231;
    $countries["VC"] = 232;
    $countries["VE"] = 233;
    $countries["VG"] = 234;
    $countries["VI"] = 235;
    $countries["VN"] = 236;
    $countries["VU"] = 237;
    $countries["WF"] = 238;
    $countries["WS"] = 239;
    $countries["YE"] = 240;
    $countries["YT"] = 241;
    $countries["ZA"] = 242;
    $countries["ZM"] = 243;
    $countries["ZW"] = 244;
    $countries["ME"] = 245;
    $countries["BL"] = 246;
    $countries["MF"] = 247;

    if(count($data->d->results) > 0){
        $sql = "UPDATE va_orders SET ";
        $where = "WHERE (";
        $case1 ="shipping_tracking_id = CASE ";
        $case2 ="order_status = CASE ";
        $case3 ="delivery_address1 = CASE ";
        $case4 ="delivery_address2 = CASE ";
        $case5 ="delivery_city = CASE ";
        $case6 ="delivery_province = CASE ";
        $case7 ="delivery_state_code = CASE ";
        $case8 ="delivery_state_id = CASE ";
        $case9 ="delivery_zip = CASE "; //delivery_country_code
        $case10 ="delivery_country_code = CASE ";
        $case11 ="delivery_country_id = CASE ";
        
        foreach ($data->d->results as $shipment){
            $case1 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".$shipment->TrackingNumber."' ";
            $case2 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '5' ";
            $case3 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".mysql_real_escape_string($shipment->Street1)."' ";
            $case4 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".mysql_real_escape_string($shipment->Street2)."' ";
            $case5 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".mysql_real_escape_string($shipment->City)."' ";
            $province = $shipment->CountryCode == 'US' ? '' : $shipment->State;
            $case6 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".mysql_real_escape_string($province)."' ";
            $state = $shipment->CountryCode != 'US' ? '' : $shipment->State;
            $case7 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".$state."' ";
            $stateID = $state != '' ?  $states[$state] : 0 ;
            $case8 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".$stateID."' ";
            $case9 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".mysql_real_escape_string($shipment->PostalCode)."' ";
            $case10 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".$shipment->CountryCode."' ";
            $case11 .="WHEN transaction_id='".$shipment->Order->OrderNumber."' THEN '".$countries[$shipment->CountryCode]."' ";
            
            $where .="transaction_id='".$shipment->Order->OrderNumber."' OR ";
        }
        $sql .= $case1."ELSE shipping_tracking_id END, ".$case2."ELSE order_status END, ".$case3."ELSE delivery_address1 END, ".$case4."ELSE delivery_address2 END, ".$case5."ELSE delivery_city END, ".$case6."ELSE delivery_province END, ".$case7."ELSE delivery_state_code END, ".$case8."ELSE delivery_state_id END, ".$case9."ELSE delivery_zip END, ".$case10."ELSE delivery_country_code END, ".$case11."ELSE delivery_country_id END ".substr($where, 0, -4).") AND order_status=4";
        //echo $sql;
        $db->query($sql);
        //mail('vital@fineonly.com', 'Shipstation data processed', $sql);
    }
    else{
        //mail('vital@fineonly.com', 'Shipstation data not processed', 'no data to process');
    }
    
}
?>
